# -*- coding: utf-8 -*-
"""simple.house.prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nqzkXNUj7tKJEmRfXhwHQOdkjZ_cXdu
"""

import pandas as pd

# Dosya yerine doğrudan veriyi DataFrame'e yazıyoruz
data = {
    "Alan (m2)": [100, 150, 120, 200, 90],
    "Oda Sayısı": [3, 4, 3, 5, 2],
    "Fiyat (TL)": [1000000, 1500000, 1200000, 2000000, 950000]
}

df = pd.DataFrame(data)

print(df)

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.scatter(df["Alan (m2)"], df["Fiyat (TL)"], color="green", marker="o")

plt.title("Alan (m²) ile Fiyat (TL) Arasındaki İlişki")
plt.xlabel("Alan (m²)")
plt.ylabel("Fiyat (TL)")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Stil ayarı (daha profesyonel görünüm)
sns.set(style="whitegrid")

# X ve Y ekseni
x = df["Alan (m2)"]
y = df["Fiyat (TL)"]

# Renkleri oda sayısına göre ayarla
colors = df["Oda Sayısı"]

# Grafik oluştur
plt.figure(figsize=(10, 6))
scatter = plt.scatter(x, y, c=colors, cmap="viridis", s=100, edgecolor="k")

# Trend çizgisi (lineer regresyon)
slope, intercept = np.polyfit(x, y, 1)
plt.plot(x, slope*x + intercept, color="red", linestyle="--", label="Trend Çizgisi")

# Başlık ve etiketler
plt.title("Alan vs Fiyat (Oda Sayısına Göre Renkli & Trend Çizgili)", fontsize=14)
plt.xlabel("Alan (m²)")
plt.ylabel("Fiyat (TL)")
plt.legend()
plt.colorbar(scatter, label="Oda Sayısı")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Ortalama fiyatı hesapla
oda_fiyat_ort = df.groupby("Oda Sayısı")["Fiyat (TL)"].mean().reset_index()

# Çubuk grafik
plt.figure(figsize=(8,5))
sns.barplot(data=oda_fiyat_ort, x="Oda Sayısı", y="Fiyat (TL)", palette="viridis")

plt.title("Oda Sayısına Göre Ortalama Fiyat")
plt.ylabel("Ortalama Fiyat (TL)")
plt.xlabel("Oda Sayısı")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
scatter = plt.scatter(
    df["Alan (m2)"], df["Fiyat (TL)"],
    s=df["Oda Sayısı"]*50,  # Oda sayısı kadar büyük baloncuk
    c=df["Oda Sayısı"],
    cmap='plasma',
    alpha=0.7,
    edgecolors='w'
)

plt.xlabel("Alan (m2)")
plt.ylabel("Fiyat (TL)")
plt.title("Baloncuk Grafiği: Alan vs Fiyat (Oda Sayısına Göre)")
plt.colorbar(scatter, label="Oda Sayısı")
plt.tight_layout()
plt.show()

sns.pairplot(df)
plt.suptitle("Değişkenler Arası İlişki", y=1.02)
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import numpy as np

# Girdiler ve hedef değişken
X = df[["Alan (m2)"]]
y = df["Fiyat (TL)"]

# Model oluşturma ve eğitme
model = LinearRegression()
model.fit(X, y)

# Tahmin ve R² hesaplama
y_pred = model.predict(X)
r2 = r2_score(y, y_pred)

print(f"R² Skoru: {r2:.2f}")

# Kullanıcıdan alan girişi al
alan = float(input("Tahmin için alan (m2) girin: "))

# Tahmin yap
tahmin = model.predict([[alan]])
print(f"Tahmini Fiyat: {tahmin[0]:,.0f} TL")